version: "3.8"

services:
  sql:
    image: sql
    build: ./sql
    restart: always
    env_file:
      - ./env/sql.env
    ports:
      - "5001:1433"

  flask_sql:
    image: flask_sql
    build: ./flask_sql
    restart: always
    depends_on:
      - sql
    env_file:
      - ./env/flask_sql.env
    ports:
      - "5000:5000"
    volumes:
      - ./flask_sql/:/app:ro

volumes:
  data: