version: "3.8"

services:
  sql:
    image: sql
    restart: always
    env_file:
      - ./env/sql.env
    ports:
      - 5001:1433
    networks:
      - 4_projeto

  flask_sql:
    image: flask_sql
    depends_on:
      - sql
    restart: always
    env_file:
      - ./env/flask_sql.env
    ports:
      - "5000:5000"
    volumes:
      - /mnt/e/git/curso_docker/5_compose/4_projeto/flask_sql:/app:ro
    networks:
      - 4_projeto

volumes:
  data:

networks:
  4_projeto: