version: "3.8"

services:
  db:
    image: mysql:8
    volumes:
      - data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  wordpress:
    depends_on:
      - db
    image: wordpress:6
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wordpress.env

volumes:
  data: