# por convenção, quando combinados em um único arquivo YAML, os services são posicionados antes dos deployments

apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-kubernetes-service"
spec:
  selector: # define quais pods receberão o tráfego do service
    app: "hello-kubernetes" # tem que ser igual ao spec.template.metadata.labels do deployment
  ports:
    - port: 5000 # porta exposta pelo service
      targetPort: 5000 # porta do container (opcional)
  type: "LoadBalancer"

---

# kubectl explain deployment
apiVersion: "apps/v1" # GROUP/VERSION
kind: "Deployment" # KIND
metadata:
  name: "hello-kubernetes-deployment"
spec:
  replicas: 3
  selector: # define quais pods serão gerenciadas por esse deployment
    matchLabels:
      app: "hello-kubernetes" # tem que ser igual ao spec.template.metadata.labels
  template: # do pod
    metadata:
      labels:
        app: "hello-kubernetes" # tem que ser igual ao spec.selector.matchLabels
    spec:
      containers:
        - name: "hello-kubernetes"
          image: "potchy/hello-kubernetes"